[package]
name = "gula"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 3
overflow-checks = false

[profile.release]
debug = 2
debug-assertions = false
overflow-checks = false

[dependencies]
typetag = "0.2.4"
enum_dispatch = "0.3.10"
paste = "1.0.11"
itertools = "0.10.5"